version: '3.8'
services:
  diagnostics_explorer:
    image: ohdsi/phepheb2024:1.0.0
    build:
      context: .
      args:
        APP_NAME: phepheb2024
    environment:
      - CONFIG_FILE=mdd.config.yml
    env_file:
      - .environ
    ports:
      - "3838:3838"
